version: '3'

services:  
  # app:
  #   build: .
  #   command: npm run start:dev
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongodb
  #     - redis
  
  mongodb:
    image: mongo:4.4.4
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - '27017:27017'
  
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'